spring:
  application:
    name: kafka-consumer-example
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: tt-group-1
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.adhithyan.kafkawithspringboot.dto

server:
  port: 9292
